[package]
name = "decrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe = { version = "0.1.6", features = [ "shortint" ] }
bincode = "1.3.3"
hex = "0.4.3"