version: "3.8"
services:
  app:
    build:
      context: .
      args:
        ZBC_FHE_TOOL_TAG: v0.1.1
    image: docker-python-zbc
    environment:
      - ZBC_FHE_TOOL_TAG=v0.1.1
    volumes:
      - ../:/home
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
